language: go
branches:
  except:
    # Avoid double testing stories which are tested as PRs.
    - /[a-zA-Z]+-\d+/
go:
- '1.13.x'
dist: bionic
addons:
  snaps:
    - name: helm
      confinement: classic
script:
  - make lint
