apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sites.fnresources.acquia.io
spec:
  group: fnresources.acquia.io
  names:
    kind: Site
    listKind: SiteList
    plural: sites
    singular: site
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certIssuer:
              type: string
            crons:
              items:
                properties:
                  command:
                    items:
                      type: string
                    type: array
                  concurrencyPolicy:
                    type: string
                  name:
                    type: string
                  schedule:
                    type: string
                  suspend:
                    type: boolean
                required:
                - name
                - command
                - schedule
                type: object
              type: array
            domains:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
            environment:
              type: string
            ingressClass:
              type: string
            install:
              properties:
                adminEmail:
                  type: string
                adminUsername:
                  type: string
                installProfile:
                  type: string
              required:
              - installProfile
              - adminUsername
              - adminEmail
              type: object
            tls:
              type: boolean
          required:
          - domains
          - environment
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
