kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fn-drupal-operator
subjects:
- kind: ServiceAccount
  name: fn-drupal-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: fn-drupal-operator
  apiGroup: rbac.authorization.k8s.io
